---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'badsectorlabs.vulhub'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'badsectorlabs.vulhub'

      - name: Trigger a new import on Galaxy.
        run: >-
          curl -v -X POST \
            -H 'Authorization: token ${{ secrets.GALAXY_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d '{"github_user": "badsectorlabs", "github_repo": "ansible-role-vulhub", "alternate_clone_url": "https://github.com/bad-sector-labs/ansible-role-vulhub", "alternate_role_name": "vulhub" }' \
            https://galaxy.ansible.com/api/v1/imports/